/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/doors.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from "../contexts/Customization";

function Doors(props) {
  const { handle, back, front } = useCustomization();
  const { nodes, materials } = useGLTF("./models/doors.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Трио_внутр_1.geometry} material={materials.Серый_металл} position={[-0.023, 1.605, -0.249]} scale={[0.56, 0.465, 0.47]} />
      <mesh geometry={nodes.Трио_внешк.geometry} material={materials.Серый_металл} visible={front === "Трио"} position={[-0.028, 1.165, 0.164]} rotation={[Math.PI / 2, 0, 0]} scale={[0.546, 1, 1]} />
      <mesh geometry={nodes.Трио_ручка.geometry} material={materials['хром светлый']} position={[-0.427, 1.055, 0.16]} scale={[0.013, 0.013, 0.016]} />
      <mesh geometry={nodes.Трио_коробка.geometry} material={materials.Серый_металл} position={[0.473, 2.115, 0.164]} scale={[-0.01, -0.016, -0.01]} />
      <mesh geometry={nodes.Трио_накладка.geometry} material={materials['хром светлый']} position={[-0.425, 1.219, 0.096]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.023, 0.008, 0.006]} />
      <group position={[-0.074, 1.443, 0.11]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.968}>
        <mesh geometry={nodes.Трио_внутр_2_1.geometry} material={materials.Трио_внутр} />
        <mesh geometry={nodes.Трио_внутр_2_2.geometry} material={materials.Трио_внутр2} />
      </group>
      <mesh geometry={nodes.Терм_Дверь_с_окном_накладка.geometry} material={materials['хром темный']} position={[-0.361, 1.248, 0.108]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.031, 0.031, 0.006]} />
      <mesh geometry={nodes.Терм_Дверь_с_окном_ручка.geometry} material={materials['хром светлый']} position={[-0.361, 0.988, 0.16]} scale={0.013} />
      <group position={[-0.02, 1.076, 0.163]} rotation={[Math.PI / 2, 0, 0]} scale={[0.501, 1, 1.059]}>
        <mesh geometry={nodes.Терм__Дверь_с_окном_внешк_1.geometry} material={materials['металл коричневый']} />
        <mesh geometry={nodes.Терм__Дверь_с_окном_внешк_2.geometry} material={materials['хром темный']} />
        <mesh geometry={nodes.Терм__Дверь_с_окном_внешк_3.geometry} material={materials['стекло матовое']} />
      </group>
      <mesh geometry={nodes.Терм__Дверь_с_окном_внутр_1.geometry} material={materials['металл бежевый']} position={[-0.023, 1.605, -0.249]} scale={[0.56, 0.465, 0.47]} />
      <group position={[-0.031, 1.07, 0.11]} rotation={[Math.PI / 2, 0, 0]} scale={[0.477, 1, 1.043]}>
        <mesh geometry={nodes.Терм__Дверь_с_окном_внутр_1_1.geometry} material={materials['металл бежевый']} />
        <mesh geometry={nodes.Терм__Дверь_с_окном_внутр_1_2.geometry} material={materials['стекло матовое']} />
      </group>
      <group position={[-0.023, 1.605, -0.302]} scale={[0.571, 0.47, 0.47]}>
        <mesh geometry={nodes.Терм__Дверь_с_окном_коробка_1.geometry} material={materials['металл коричневый']} />
        <mesh geometry={nodes.Терм__Дверь_с_окном_коробка_2.geometry} material={materials['хром светлый']} />
      </group>
      <group position={[-0.407, 1.13, 0.107]} rotation={[Math.PI / 2, 0, 0]} scale={[0.007, 0.008, 0.007]}>
        <mesh geometry={nodes.Эконом1_накладка_1.geometry} material={materials['хром светлый']} />
        <mesh geometry={nodes.Эконом1_накладка_2.geometry} material={materials['хром светлый']} />
      </group>
      <mesh geometry={nodes.Эконом1_ручка.geometry} material={materials['хром светлый']} position={[-0.407, 1.041, 0.077]} rotation={[-Math.PI / 2, 0, 0]} scale={0.033} />
      <mesh geometry={nodes.Эконом1_внешк.geometry} material={materials['металл коричневый']} position={[-0.02, 1.076, 0.163]} rotation={[Math.PI / 2, 0, 0]} scale={[0.501, 1, 1.059]} />
      <mesh geometry={nodes.Эконом1_внутр_1.geometry} material={materials['металл коричневый']} position={[-0.023, 1.605, -0.249]} scale={[0.56, 0.465, 0.47]} />
      <mesh geometry={nodes.Эконом1_внутр_2.geometry} material={materials.Эконом1_панель} position={[-0.061, 1.06, 0.109]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1.049]} />
      <group position={[-0.023, 1.605, -0.302]} scale={[0.572, 0.47, 0.47]}>
        <mesh geometry={nodes.Эконом1_коробка_1.geometry} material={materials['металл коричневый']} />
        <mesh geometry={nodes.Эконом1_коробка_2.geometry} material={materials['хром светлый']} />
      </group>
      <group position={[-1.565, 0.785, 0.038]} rotation={[0, -1.571, 0]} scale={[0.443, 0.538, 0.133]}>
        <mesh geometry={nodes.сцена1_1.geometry} material={materials['пластик черный']} />
        <mesh geometry={nodes.сцена1_2.geometry} material={materials.пластик} />
        <mesh geometry={nodes.сцена1_3.geometry} material={materials['плитка светлая']} />
        <mesh geometry={nodes.сцена1_4.geometry} material={materials['мрамор матовый']} />
        <mesh geometry={nodes.сцена1_5.geometry} material={materials.кирпич} />
        <mesh geometry={nodes.сцена1_6.geometry} material={materials['мрамор плитка']} />
        <mesh geometry={nodes.сцена1_7.geometry} material={materials.материал} />
        <mesh geometry={nodes.сцена1_8.geometry} material={materials['хром светлый']} />
        <mesh geometry={nodes.сцена1_9.geometry} material={materials['дерево темное']} />
        <mesh geometry={nodes.сцена1_10.geometry} material={materials['дерево светлое']} />
        <mesh geometry={nodes.сцена1_11.geometry} material={materials.резина} />
        <mesh geometry={nodes.сцена1_12.geometry} material={materials['тапки 2']} />
        <mesh geometry={nodes.сцена1_13.geometry} material={materials.ткань} />
        <mesh geometry={nodes.сцена1_14.geometry} material={materials['стекло матовое']} />
        <mesh geometry={nodes.сцена1_15.geometry} material={materials['хром темный']} />
        <mesh geometry={nodes.сцена1_16.geometry} material={materials.кровля} />
        <mesh geometry={nodes.сцена1_17.geometry} material={materials.Земля2} />
        <mesh geometry={nodes.сцена1_18.geometry} material={materials.ствол_туи} />
        <mesh geometry={nodes.сцена1_19.geometry} material={materials.листья_туи} />
      </group>
      <group position={[-1.565, 0.785, 0.038]} rotation={[0, -1.571, 0]} scale={[0.443, 0.538, 0.133]}>
        <mesh geometry={nodes.сцена2_1.geometry} material={materials['пластик черный']} />
        <mesh geometry={nodes.сцена2_2.geometry} material={materials.пластик} />
        <mesh geometry={nodes.сцена2_3.geometry} material={materials['дерево темное']} />
        <mesh geometry={nodes.сцена2_4.geometry} material={materials['дерево светлое']} />
        <mesh geometry={nodes.сцена2_5.geometry} material={materials.Земля2} />
        <mesh geometry={nodes.сцена2_6.geometry} material={materials.ствол_туи} />
        <mesh geometry={nodes.сцена2_7.geometry} material={materials.материал} />
        <mesh geometry={nodes.сцена2_8.geometry} material={materials['серый светлый']} />
        <mesh geometry={nodes.сцена2_9.geometry} material={materials.металлик} />
        <mesh geometry={nodes.сцена2_10.geometry} material={materials.бронза} />
        <mesh geometry={nodes.сцена2_11.geometry} material={materials.ткань2} />
        <mesh geometry={nodes.сцена2_12.geometry} material={materials.Ткань_зонтика} />
        <mesh geometry={nodes.сцена2_13.geometry} material={materials['дерево белое']} />
        <mesh geometry={nodes.сцена2_14.geometry} material={materials.ваза} />
        <mesh geometry={nodes.сцена2_15.geometry} material={materials.ткань_пуфа} />
        <mesh geometry={nodes.сцена2_16.geometry} material={materials.мрамор} />
        <mesh geometry={nodes.сцена2_17.geometry} material={materials.крыша} />
        <mesh geometry={nodes.сцена2_18.geometry} material={materials.дерево} />
        <mesh geometry={nodes.сцена2_19.geometry} material={materials.стены} />
        <mesh geometry={nodes.сцена2_20.geometry} material={materials['керамическая крыша']} />
        <mesh geometry={nodes.сцена2_21.geometry} material={materials.мрамор55} />
        <mesh geometry={nodes.сцена2_22.geometry} material={materials.ветки} />
        <mesh geometry={nodes.сцена2_23.geometry} material={materials.растение} />
        <mesh geometry={nodes.сцена2_24.geometry} material={materials.Мрамор_серо_белый} />
        <mesh geometry={nodes.сцена2_25.geometry} material={materials.материал} />
      </group>
    </group>
  )
}


useGLTF.preload("./models/doors.gltf");

export default Doors;